from django.urls import include, path

from . import views

app_name = 'teachadmin'

homeroom_patterns = [
    path('all/',
        views.HomeRoomListView.as_view(),
        name='homeroom_list'),
    path('new/',
        views.HomeRoomCreateView.as_view(),
        name='homeroom_new'),
    path('<int:pk>/',
        views.HomeRoomDetailView.as_view(),
        name='homeroom_detail'),
    path('<int:pk>/delete/',
        views.HomeRoomDeleteView.as_view(),
        name='homeroom_delete'),
    path('<int:pk>/update/',
        views.HomeRoomUpdateView.as_view(),
        name='homeroom_update'),
    path('<int:pk>/update/<subject>/',
        views.HomeRoomUpdateView.as_view(),
        name='homeroom_update')
]

school_patterns = [
    path('all/',
        views.SchoolListView.as_view(),
        name='school_list'),
    path('new/',
        views.SchoolCreateView.as_view(),
        name='new_school'),
    path('<int:pk>/',
        views.SchoolDetailView.as_view(),
        name='school_detail'),
    path('<int:pk>/delete/',
        views.SchoolDeleteView.as_view(),
        name='school_delete'),
    path('<int:pk>/update/',
        views.SchoolUpdateView.as_view(),
        name='school_update'),
    path('<int:school_pk>/homerooms/new/',
        views.HomeRoomCreateView.as_view(),
        name='school_add_homeroom')
]

student_patterns = [
    path('all/',
        views.StudentListView.as_view(),
        name='student_list'),
    path('new/',
        views.StudentCreateView.as_view(),
        name='student_new'),
    path('others/',
        views.OtherStudentsList.as_view(),
        name='other_students_list'),
    path('<int:pk>/',
        views.StudentDetailView.as_view(),
        name='student_detail'),
    path('<int:pk>/update/',
        views.StudentUpdateView.as_view(),
        name='student_update'),
    path('<int:pk>/delete/',
        views.StudentDeleteView.as_view(),
        name='student_delete')
]

subject_patterns = [
    path('all/',
        views.SubjectListView.as_view(),
        name='subject_list'),
    path('new/', 
        views.SubjectCreateView.as_view(),
        name='subject_new'),
    path('<int:pk>/delete/',
        views.SubjectDeleteView.as_view(),
        name='subject_delete'),
    path('new/<int:student_pk>/',
        views.SubjectCreateView.as_view(),
        name='subject_new_student'),
    path('<int:pk>/',
        views.SubjectDetailView.as_view(),
        name='subject_detail'),
    path('<int:pk>/add-student/',
        views.SubjectUpdateView.as_view(),
        name='subject_add_student'),
    path('<int:subject_pk>/add-exam/',
        views.ExamCreateView.as_view(),
        name='subject_add_exam'),
    path('<int:subject_pk>/exams/',
        views.ExamListView.as_view(),
        name='exam_list'),
    path('<int:subject_pk>/exams/<int:pk>/',
        views.ExamDetailView.as_view(),
        name='exam_detail'),
    path('<int:subject_pk>/exams/<int:pk>/update/',
        views.ExamUpdateView.as_view(),
        name='exam_update'),
    path('<int:subject_pk>/exams/<int:pk>/delete/',
        views.ExamDeleteView.as_view(),
        name='exam_delete'),
    path('<int:subject_pk>/exams/<int:exam_pk>/scores/new/',
        views.ExamScoreCreateView.as_view(),
        name='subject_exam_add_score'),
    path('<int:subject_pk>/exams/<int:exam_pk>/scores/<int:pk>/',
        views.ExamScoreDetailView.as_view(),
        name='examscore_detail'),
    path('<int:subject_pk>/exams/<int:exam_pk>/scores/<int:pk>/update/',
        views.ExamScoreUpdateView.as_view(),
        name='examscore_update'),
    path('<int:subject_pk>/exams/<int:exam_pk>/scores/<int:pk>/delete/',
        views.ExamScoreDeleteView.as_view(),
        name='examscore_delete'),
    path('<int:subject_pk>/add-lesson/',
        views.LessonCreateView.as_view(),
        name='subject_add_lesson'),
    path('<int:subject_pk>/lessons/<int:pk>/',
        views.LessonDetailView.as_view(),
        name='lesson_detail'),
    path('<int:subject_pk>/lessons/<int:pk>/update/',
        views.LessonUpdateView.as_view(),
        name='lesson_update'),
    path('<int:subject_pk>/lessons/<int:pk>/delete/',
        views.LessonDeleteView.as_view(),
        name='lesson_delete'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/homework/new/',
        views.HomeworkCreateView.as_view(),
        name='lesson_add_homework'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/homework/<int:pk>/',
        views.HomeworkDetailView.as_view(),
        name='homework_detail'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/homework/<int:pk>/update/',
        views.HomeworkUpdateView.as_view(),
        name='homework_update'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/homework/<int:pk>/delete/',
        views.HomeworkDeleteView.as_view(),
        name='homework_delete'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/homework/<int:homework_pk>/add-score/',
        views.HomeworkScoreCreateView.as_view(),
        name='homework_add_score'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/new/',
        views.LessonTestCreateView.as_view(),
        name='lesson_add_test'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:pk>/',
        views.LessonTestDetailView.as_view(),
        name='lessontest_detail'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:pk>/update/',
        views.LessonTestUpdateView.as_view(),
        name='lessontest_update'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:pk>/delete/',
        views.LessonTestDeleteView.as_view(),
        name='lessontest_delete'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:lessontest_pk>/testscores/new/',
        views.LessonTestScoreCreateView.as_view(),
        name='lessontest_add_score'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:lessontest_pk>/testscores/<int:pk>/',
        views.LessonTestScoreDetailView.as_view(),
        name='lessontestscore_detail'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:lessontest_pk>/testscores/<int:pk>/update/',
        views.LessonTestScoreUpdateView.as_view(),
        name='lessontestscore_update'),
    path('<int:subject_pk>/lessons/<int:lesson_pk>/tests/<int:lessontest_pk>/testscores/<int:pk>/delete/',
        views.LessonTestScoreDeleteView.as_view(),
        name='lessontestscore_delete'),
    path('<int:subject_pk>/assignments/<int:pk>/',
        views.AssignmentDetailView.as_view(),
        name='assignment_detail'),
    path('<int:subject_pk>/assignments/new/',
        views.AssignmentCreateView.as_view(),
        name='subject_add_assignment'),
    path('<int:subject_pk>/assignments/<int:pk>/update/',
        views.AssignmentUpdateView.as_view(),
        name='assignment_update'),
    path('<int:subject_pk>/assignments/<int:pk>/delete/',
        views.AssignmentDeleteView.as_view(),
        name='assignment_delete'),
    path('<int:subject_pk>/assignment/<int:assignment_pk>/add_score/',
        views.AssignmentScoreCreateView.as_view(),
        name='assignment_add_score')
]

teacher_patterns = [
    path('<int:pk>/', views.TeacherDetailView.as_view(), name='teacher'),
]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.register, name='register'),
    path('logout/', views.teachadmin_logout, name='logout'),
    path('login/', views.teachadmin_login, name='login'),
    path('addSchool/', views.addSchool, name='addSchool'),
    path('homeroom/', include(homeroom_patterns)),
    path('schools/', include(school_patterns)),
    path('student/', include(student_patterns)),
    path('subjects/', include(subject_patterns)),
    path('teacher/', include(teacher_patterns)),
]
