# Generated by Django 3.0.6 on 2020-05-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachadmin.School'),
        ),
    ]
