# Generated by Django 3.0.6 on 2020-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0004_auto_20200608_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Female', max_length=6),
        ),
    ]
