# Generated by Django 3.0.6 on 2020-06-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0005_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tests',
        ),
        migrations.AddField(
            model_name='student',
            name='tests',
            field=models.ManyToManyField(null=True, to='teachadmin.StudentClassTest'),
        ),
        migrations.RemoveField(
            model_name='studentclasstest',
            name='studentClass',
        ),
        migrations.AddField(
            model_name='studentclasstest',
            name='studentClass',
            field=models.ManyToManyField(null=True, to='teachadmin.StudentClass'),
        ),
    ]
