# Generated by Django 3.0.6 on 2020-06-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0007_auto_20200609_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentClass',
        ),
        migrations.AddField(
            model_name='student',
            name='studentClass',
            field=models.ManyToManyField(to='teachadmin.StudentClass'),
        ),
    ]
