# Generated by Django 3.0.6 on 2020-06-11 02:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0010_auto_20200609_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ['grade', 'name']},
        ),
        migrations.AddField(
            model_name='studentclasstest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 2, 39, 39, 811917, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentClassTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.StudentClassTest')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('turn_in_date', models.DateTimeField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='studentClass',
            field=models.ManyToManyField(to='teachadmin.StudentClass'),
        ),
    ]
