# Generated by Django 3.0.6 on 2020-06-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0011_auto_20200611_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclasstest',
            options={'ordering': ['name', 'date']},
        ),
        migrations.AlterModelOptions(
            name='studentclasstestscore',
            options={'ordering': ['test', 'score']},
        ),
    ]
