# Generated by Django 3.0.6 on 2020-06-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0012_auto_20200612_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentscore',
            options={'ordering': ['assignment', 'turn_in_date', 'score']},
        ),
        migrations.RemoveField(
            model_name='assignmentscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentclasstestscore',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='assignment_scores',
            field=models.ManyToManyField(to='teachadmin.AssignmentScore'),
        ),
        migrations.AddField(
            model_name='student',
            name='test_scores',
            field=models.ManyToManyField(to='teachadmin.StudentClassTestScore'),
        ),
    ]
