# Generated by Django 3.0.6 on 2020-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0014_auto_20200613_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasstest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
