# Generated by Django 3.0.6 on 2020-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0016_auto_20200707_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='creator',
            field=models.ManyToManyField(to='teachadmin.Teacher'),
        ),
        migrations.AddField(
            model_name='studentclasstest',
            name='creator',
            field=models.ManyToManyField(to='teachadmin.Teacher'),
        ),
    ]
