# Generated by Django 3.0.6 on 2020-07-14 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0017_auto_20200709_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.School')),
                ('teacher', models.ManyToManyField(to='teachadmin.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('test_date', models.DateField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('homeroom', models.ManyToManyField(to='teachadmin.HomeRoom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.School')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('lessonTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.LessonTest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
            ],
            options={
                'ordering': ['lessonTest', 'student'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Subject'),
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
            ],
            options={
                'ordering': ['exam', 'student'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Subject'),
        ),
        migrations.CreateModel(
            name='BehaviorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
                ('behaviorType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.BehaviorType')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachadmin.Teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
            ],
            options={
                'ordering': ['timestamp', 'student', 'behaviorType'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='homeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachadmin.HomeRoom'),
        ),
    ]
