# Generated by Django 3.0.6 on 2020-07-14 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0018_auto_20200714_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Lesson')),
            ],
            options={
                'ordering': ['lesson', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=10),
        ),
        migrations.CreateModel(
            name='HomeworkScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Student')),
            ],
            options={
                'ordering': ['student', 'homework'],
            },
        ),
    ]
