# Generated by Django 3.0.6 on 2020-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0019_auto_20200714_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teacher',
            field=models.ManyToManyField(to='teachadmin.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to='teachadmin.Teacher'),
        ),
    ]
