# Generated by Django 3.0.6 on 2020-07-23 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0023_auto_20200723_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behaviorevent',
            options={'ordering': ['timestamp', 'student', 'behaviorType', 'creator']},
        ),
        migrations.AlterModelOptions(
            name='behaviortype',
            options={'ordering': ['name', 'teacher']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['subject', 'date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='examscore',
            options={'ordering': ['exam', 'student', 'score']},
        ),
        migrations.AlterModelOptions(
            name='homeworkscore',
            options={'ordering': ['student', 'homework', 'score']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['subject', 'name']},
        ),
        migrations.AlterModelOptions(
            name='lessontest',
            options={'ordering': ['lesson', 'test_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['school', 'name']},
        ),
        migrations.AddField(
            model_name='examscore',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
