# Generated by Django 3.0.6 on 2020-07-23 06:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0024_auto_20200723_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
