# Generated by Django 3.0.6 on 2020-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0025_auto_20200723_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
