# Generated by Django 3.0.6 on 2020-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0027_auto_20200724_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
