# Generated by Django 3.0.6 on 2020-07-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0028_homeroom_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachadmin.School'),
        ),
    ]
