# Generated by Django 3.0.6 on 2020-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0029_auto_20200725_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='teachadmin.Teacher'),
        ),
    ]
