# Generated by Django 3.0.6 on 2020-07-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0030_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeroom',
            options={'ordering': ['name', 'grade', 'school']},
        ),
    ]
