# Generated by Django 3.0.6 on 2020-08-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0031_auto_20200730_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examscore',
            options={'ordering': ['exam', 'score', 'student']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'school']},
        ),
    ]
