# Generated by Django 3.0.6 on 2020-08-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0033_auto_20200819_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['name', 'deadline', 'subject']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='studentClass',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='teachadmin.Subject'),
            preserve_default=False,
        ),
    ]
