# Generated by Django 3.0.6 on 2020-09-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0037_auto_20200902_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeroom',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Positive numbers.', null=True),
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='school',
            field=models.ForeignKey(help_text='Choose one.', on_delete=django.db.models.deletion.CASCADE, to='teachadmin.School'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Anything within 50 characters.', max_length=50),
        ),
    ]
