# Generated by Django 3.0.6 on 2020-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0038_auto_20200902_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='homerooms/csv/'),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, help_text='(Optional) English, please...', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='teachers/profile_pics/'),
        ),
    ]
