# Generated by Django 3.0.6 on 2020-09-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0039_auto_20200906_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homeroom',
            name='document',
        ),
        migrations.RemoveField(
            model_name='homeroom',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='homeroom',
            name='homeroomfile',
            field=models.FileField(blank=True, help_text='File format: .csv', upload_to='homerooms/csv/'),
        ),
    ]
