# Generated by Django 3.0.6 on 2020-09-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0040_auto_20200906_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroom',
            name='homeroomfile',
        ),
    ]
