# Generated by Django 3.0.6 on 2020-09-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0041_remove_homeroom_homeroomfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name', 'student_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
