# Generated by Django 3.0.6 on 2020-09-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0043_auto_20200908_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['start_date', 'subject', 'name']},
        ),
    ]
