# Generated by Django 3.0.6 on 2020-09-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0045_auto_20200908_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
