# Generated by Django 3.0.6 on 2020-09-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0046_auto_20200915_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasstest',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='studentclasstest',
            name='studentClass',
        ),
        migrations.RemoveField(
            model_name='studentclasstestscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentclasstestscore',
            name='test',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentClass',
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Within 50 characters.', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='Optional. Within 50 characters.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, help_text='Optional. Within 50 characters.', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='StudentClassTest',
        ),
        migrations.DeleteModel(
            name='StudentClassTestScore',
        ),
    ]
