# Generated by Django 3.0.6 on 2020-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0047_auto_20200916_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='Within 50 characters.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, help_text='Within 50 characters.', max_length=20, null=True),
        ),
    ]
