# Generated by Django 3.0.6 on 2020-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0049_auto_20200921_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontest',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Default: 100'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='min_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Default: 0'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='name',
            field=models.CharField(help_text='Within 50 characters.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='test_date',
            field=models.DateField(blank=True, help_text='Format: yyyy-mm-dd'),
        ),
    ]
