# Generated by Django 3.0.6 on 2020-09-23 08:17

from django.db import migrations, models

def last_name_fix(apps, schema_editor):
    Student = apps.get_model('teachadmin', 'student')
    for student in Student.objects.filter(last_name=None):
        student.last_name = ''
        student.save(update_fields=['last_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0051_auto_20200922_2055'),
    ]

    operations = [
        migrations.RunPython(last_name_fix),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Within 50 characters.', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, default='', help_text='Within 50 characters.', max_length=20),
        ),
    ]
