# Generated by Django 3.0.6 on 2020-10-02 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0054_auto_20200928_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontest',
            options={'ordering': ['test_date', 'lesson', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 2), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='test_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 2), help_text='Format: yyyy-mm-dd'),
        ),
    ]
