# Generated by Django 3.0.6 on 2020-10-06 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0056_auto_20201006_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkscore',
            name='turn_in_date',
        ),
        migrations.AddField(
            model_name='homeworkscore',
            name='turn_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
