# Generated by Django 3.0.6 on 2020-10-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0057_auto_20201006_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkscore',
            name='turn_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Format: YYYY-MM-DD HH:MM:SS'),
        ),
    ]
