# Generated by Django 3.0.6 on 2020-10-07 05:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0058_auto_20201006_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentscore',
            options={'ordering': ['assignment', 'turn_in_time', 'score']},
        ),
        migrations.RemoveField(
            model_name='assignmentscore',
            name='turn_in_date',
        ),
        migrations.AddField(
            model_name='assignmentscore',
            name='turn_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 7), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='test_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 7), help_text='Format: yyyy-mm-dd'),
        ),
    ]
