# Generated by Django 3.0.6 on 2020-10-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0061_auto_20201007_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 8), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='lessontest',
            name='test_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 8), help_text='Format: yyyy-mm-dd'),
        ),
    ]
