# Generated by Django 3.0.6 on 2020-10-08 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0062_auto_20201008_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Within 30 characters.', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Start date'),
        ),
    ]
