# Generated by Django 3.0.6 on 2020-10-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachadmin', '0063_auto_20201008_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontest',
            name='test_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 18), help_text='Format: yyyy-mm-dd'),
        ),
    ]
